In [1]:
import pandas as pd
import glob
import matplotlib.pyplot as plt

/home/diego/.local/lib/python3.12/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "

Limpieza en masa de duplicados

In [2]:
ruta = "../data/clean/*.csv"
archivos = glob.glob(ruta)

MIN_DELTA = 1
MAX_DELTA = 5

In [ ]:
for archivo in archivos:
    print("Procesando:", archivo)

    df = pd.read_csv(archivo)
    df["timestamp"] = pd.to_datetime(df["timestamp"])
    df = df.sort_values("timestamp").reset_index(drop=True)

    # Paso 1: eliminar duplicados exactos (timestamp + evento)
    df = df.drop_duplicates(subset=["timestamp", "evento"], keep="first")

    # Paso 2: eliminar duplicados con < 5 segundos de desfase
    diffs = df["timestamp"].diff().dt.total_seconds().fillna(9999)

    # Crear mascara y eliminar
    mask = (diffs > MIN_DELTA) & (diffs < MAX_DELTA)

    df = df[~mask].reset_index(drop=True)

    # Guardar archivos
    nuevo = archivo.replace(".csv", "_clean.csv")
    df.to_csv(nuevo, index=False)
    print("Guardado:", nuevo)

Limpieza enfocada (Timestamp duplicado, evento distinto)

In [23]:
df = pd.read_csv("../data/clean/day_1_cleanest.csv")
df["timestamp"] = pd.to_datetime(df["timestamp"])

df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  104 non-null    datetime64[ns]
 1   evento     104 non-null    object
dtypes: datetime64[ns](1), object(1)
memory usage: 1.8+ KB

/tmp/ipykernel_5791/2714168130.py:5: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df.describe()

                  timestamp  evento
count                   104     104
unique                  104       2
top     2025-11-10 06:25:01  salida
freq                      1      56
first   2025-11-10 06:25:01     NaN
last    2025-11-10 20:55:30     NaN

Media, picos Max & Min

In [26]:
archivos = glob.glob("../data/clean/*.csv")
resultados = []

for archivo in archivos:
    df = pd.read_csv(archivo)
    df["timestamp"] = pd.to_datetime(df["timestamp"])

    df["fecha"] = df["timestamp"].dt.date
    df["hora"] = df["timestamp"].dt.hour

    fecha = df["fecha"].iloc[0]

    entradas = (df["evento"] == "entrada").sum()
    salidas = (df["evento"] == "salida").sum()

    hora_pico_entrada = (
        df[df["evento"] == "entrada"]["hora"]
        .value_counts()
        .idxmax()
        if entradas > 0 else None
    )

    hora_pico_salida = (
        df[df["evento"] == "salida"]["hora"]
        .value_counts()
        .idxmax()
        if salidas > 0 else None
    )

    resultados.append({
        "fecha": fecha,
        "entradas": entradas,
        "salidas": salidas,
        "hora_pico_entrada": hora_pico_entrada,
        "hora_pico_salida": hora_pico_salida
    })

resumen_diario = pd.DataFrame(resultados)

In [27]:
resumen_diario.to_csv("../data/resumen_diario.csv", index=False)

In [ ]:
df["timestamp"].value_counts()[lambda x: x > 1]

Duplicados Timestamp

In [78]:
duplicados = df[df["timestamp"].duplicated(keep=False)].sort_values("timestamp")

duplicados

Empty DataFrame
Columns: [timestamp, evento]
Index: []

Revision Manual de video

In [212]:
df = df.drop(62)

In [214]:
df.to_csv("../data/clean/day_22_cleanest.csv", index=False)

Borrar columnas

In [ ]:
for archivo in archivos:
    print("Borrado de columnas:", archivo)
    df = pd.read_csv(archivo)
    columnas_borrar = ["frame_idx", "track_id", "clase", "cx", "cy", "x1", "x2", "y1", "y2"]
    df = df.drop(columns=[c for c in columnas_borrar if c in df.columns])

    df.to_csv(archivo, index=False)
    print("Columnas borradas")

Build daily and hour graphics

In [ ]:
df["timestamp"] = pd.to_datetime(df["timestamp"])
df["hora"] = df["timestamp"].dt.hour
conteo = df.groupby(["hora", "evento"]).size().unstack(fill_value=0)

plt.figure(figsize=(5,12))

ax = conteo.plot(
    kind="bar",
    figsize=(9,5),
    color={"entrada": "orange", "salida": "grey"},
)

plt.xlabel("Hora del dia")
plt.ylabel("Entradas y salidas")
plt.title("Mie, Nov 19")
plt.xticks(rotation=0)
plt.grid(axis="y")

total_entradas = conteo["entrada"].sum() if "entrada" in conteo.columns else 0
total_salidas = conteo["salida"].sum() if "salida" in conteo.columns else 0

texto = f"Entradas: {total_entradas}\nSalidas: {total_salidas}"

plt.text(
    0.70, 0.95, texto,
    transform=ax.transAxes,
    ha="right", va="top",
    fontsize=10,
    bbox=dict(facecolor="white", alpha=0.6, edgecolor="none")
)

plt.savefig("../graph/day10", dpi=300, bbox_inches="tight")
plt.show()

Build weekly graphics

In [ ]:
archivos = glob.glob("../data/clean/*.csv")

resumen = []

for archivo in archivos:
    df = pd.read_csv(archivo)
    df["timestamp"] = pd.to_datetime(df["timestamp"])

    fecha = df["timestamp"].dt.date.iloc[0]

    entradas = (df["evento"] == "entrada").sum()
    salidas = (df["evento"] == "salida").sum()

    etiqueta = df["timestamp"].dt.strftime("%a %b %d").iloc[0]

    resumen.append([etiqueta, fecha, entradas, salidas])

resumen_df = pd.DataFrame(resumen, columns=["etiqueta", "fecha_real", "entrada", "salida"])

resumen_df = resumen_df.sort_values("fecha_real")

plt.figure(figsize=(12,6))

resumen_df.set_index("etiqueta")[["entrada", "salida"]].plot(
    kind="bar",
    figsize=(12,6),
    color={"entrada": "orange", "salida": "grey"}
)

plt.xlabel("Día")
plt.ylabel("Número de eventos")
plt.title("Entradas y salidas por día")
plt.xticks(rotation=45, ha="right")
plt.grid(axis="y")

plt.tight_layout()
plt.savefig("../graph/resumen_diario.png", dpi=300)
plt.show()

Sort final values

In [2]:
df = pd.read_csv("../data/clean/resumen_diario.csv")

In [5]:
df.sort_values("salidas")

         fecha  entradas  salidas  hora_pico_entrada  hora_pico_salida
3   2025-11-23        30       29                 16                16
20  2025-11-30        32       30                 20                14
16  2025-11-22        30       32                 19                17
6   2025-11-29        34       35                 13                 9
0   2025-11-15        47       39                 20                10
15  2025-11-16        49       41                 13                12
13  2025-11-12        42       42                 18                 7
9   2025-11-18        46       44                 12                 7
7   2025-11-28        54       47                 16                16
11  2025-11-21        51       47                 12                19
14  2025-11-13        48       48                 18                 7
2   2025-11-20        48       50                 18                15
19  2025-11-25        49       50                 19                 7
17  2025-11-27        54       50                 16                16
4   2025-11-24        59       50                 18                 8
12  2025-11-17        64       51                 18                 7
1   2025-11-26        59       51                 20                 7
10  2025-11-10        48       56                 19                 9
18  2025-11-14        53       57                 15                 7
5   2025-11-19        66       59                 17                14
8   2025-11-11        64       66                 18                 8